rulesets:
  - name: "Protect main branch"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "main"
          - "master"
    rules:
      # Require PRs and restrict direct pushes
      - type: required_pull_request
        parameters:
          require_code_owner_review: false
          required_approving_review_count: 1
          dismiss_stale_reviews_on_push: true
          require_last_push_approval: true
      - type: restrict_pushes
        parameters:
          push_allowances: []
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - terraform
      - type: restrict_bypasses
        parameters:
          bypass_allowances: []

  - name: "Require merges from dev"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "main"
          - "master"
    rules:
      - type: restrict_pushes
        parameters:
          push_allowances:
            - repository_role: "none"
      - type: restrict_deletions
        parameters:
          deletion_allowances:
            - repository_role: "none"
      - type: required_linear_history
      - type: required_pull_request
        parameters:
          required_approving_review_count: 1
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - terraform

  - name: "Protect dev branch (cannot be deleted)"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "dev"
    rules:
      - type: restrict_deletions
        parameters:
          deletion_allowances: []
      - type: restrict_pushes
        parameters:
          push_allowances:
            - actor_id: serhiipuzyrov
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - terraform

  - name: "Restrict branch creation"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "*"
    rules:
      - type: restrict_creation
        parameters:
          creation_allowances:
            - actor_id: serhiipuzyrov
      - type: restrict_pushes
        parameters:
          push_allowances:
            - actor_id: serhiipuzyrov