project_id = "data-platform-dev-477621"
env = "dev"
multi_region = "EU"
region = "europe-central2"
github_org = "serhiipuzyrov"
github_repo_infra = "data-platform-infra"
github_repo_dbt = "data-platform-dbt"
alert_email = "test@gmail.com"